apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
    name: k8ace-matrix-nvidia-sd-webui-1-10-0-sd-webui-cuda
    namespace: default
spec:
    entrypoint: main
    serviceAccountName: argo-workflow
    templates:
        - name: main
          dag:
            tasks:
                - name: base-image-nvidia-cuda-base-cuda12-4-devel-ubuntu22-04
                  template: base-image-nvidia-cuda-base-cuda12-4-devel-ubuntu22-04
                - name: app-image-nvidia-sd-webui-1-10-0-sd-webui-cuda
                  template: app-image-nvidia-sd-webui-1-10-0-sd-webui-cuda
                  dependencies:
                    - base-image-nvidia-cuda-base-cuda12-4-devel-ubuntu22-04
                - name: host-driver-nvidia-sd-webui-1-10-0-sd-webui-cuda
                  template: host-driver-nvidia-sd-webui-1-10-0-sd-webui-cuda
                  dependencies:
                    - app-image-nvidia-sd-webui-1-10-0-sd-webui-cuda
                - name: test-nvidia-sd-webui-1-10-0-sd-webui-cuda
                  template: test-nvidia-sd-webui-1-10-0-sd-webui-cuda
                  dependencies:
                    - host-driver-nvidia-sd-webui-1-10-0-sd-webui-cuda
                - name: push-nvidia-sd-webui-1-10-0-sd-webui-cuda
                  template: push-nvidia-sd-webui-1-10-0-sd-webui-cuda
                  dependencies:
                    - test-nvidia-sd-webui-1-10-0-sd-webui-cuda
        - name: base-image-nvidia-cuda-base-cuda12-4-devel-ubuntu22-04
          container:
            image: gcr.io/kaniko-project/executor:latest
            command:
                - /kaniko/executor
            args:
                - --context=.
                - --dockerfile=dockerfiles/base_image/nvidia/cuda_base/cuda12.4-devel-ubuntu22.04/Dockerfile
                - --destination=k8ace/cuda_base-cuda12.4-devel-ubuntu22.04
                - --cache=true
                - --cache-repo=k8ace/cache/nvidia/base_image
                - --build-arg=BASE_IMAGE=nvidia/cuda:cuda12.4-devel-ubuntu22.04
            volumeMounts:
                - name: registry-config
                  mountPath: /kaniko/.docker
                  readOnly: true
        - name: app-image-nvidia-sd-webui-1-10-0-sd-webui-cuda
          container:
            image: gcr.io/kaniko-project/executor:latest
            command:
                - /kaniko/executor
            args:
                - --context=.
                - --dockerfile=dockerfiles/app_image/nvidia/sd_webui/1.10.0/sd-webui-cuda/Dockerfile
                - --destination=k8ace/sd_webui1.10.0-nvidia-sd-webui-cuda-dev
                - --cache=true
                - --cache-repo=k8ace/cache/nvidia/app_image
                - --build-arg=BASE_IMAGE=k8ace/cuda_base-cuda12.4-devel-ubuntu22.04
                - --build-arg=GPU_ARCH=all
                - --build-arg=NVCC_FLAGS=-gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90
            volumeMounts:
                - name: registry-config
                  mountPath: /kaniko/.docker
                  readOnly: true
        - name: host-driver-nvidia-sd-webui-1-10-0-sd-webui-cuda
          container:
            image: gcr.io/kaniko-project/executor:latest
            command:
                - /kaniko/executor
            args:
                - --context=.
                - --dockerfile=dockerfiles/host_driver/noop/Dockerfile
                - --destination=k8ace/noop-host-driver-nvidia-sd-webui-1-10-0-sd-webui-cuda
                - --cache=true
                - --cache-repo=k8ace/cache/nvidia/host_driver
                - --no-push
                - --build-arg=BASE_IMAGE=alpine:3.20
            volumeMounts:
                - name: registry-config
                  mountPath: /kaniko/.docker
                  readOnly: true
        - name: test-nvidia-sd-webui-1-10-0-sd-webui-cuda
          container:
            image: gcr.io/kaniko-project/executor:latest
            command:
                - /kaniko/executor
            args:
                - --context=.
                - --dockerfile=dockerfiles/test/noop/Dockerfile
                - --destination=k8ace/noop-test-nvidia-sd-webui-1-10-0-sd-webui-cuda
                - --cache=true
                - --cache-repo=k8ace/cache/nvidia/test
                - --no-push
                - --build-arg=BASE_IMAGE=alpine:3.20
            volumeMounts:
                - name: registry-config
                  mountPath: /kaniko/.docker
                  readOnly: true
        - name: push-nvidia-sd-webui-1-10-0-sd-webui-cuda
          container:
            image: gcr.io/kaniko-project/executor:latest
            command:
                - /kaniko/executor
            args:
                - --context=.
                - --dockerfile=dockerfiles/push/noop/Dockerfile
                - --destination=k8ace/noop-push-nvidia-sd-webui-1-10-0-sd-webui-cuda
                - --cache=true
                - --cache-repo=k8ace/cache/nvidia/push
                - --no-push
                - --build-arg=BASE_IMAGE=alpine:3.20
            volumeMounts:
                - name: registry-config
                  mountPath: /kaniko/.docker
                  readOnly: true
    volumes:
        - name: registry-config
          secret:
            secretName: registry-credentials
            items:
                - key: .dockerconfigjson
                  path: config.json
